import type { SelectorCandidate } from '../../shared/types'
import type { ElementSignals } from './observer'

/**
 * Estrategia de selectores (§4). El frontend documentado es Next.js, así que
 * las clases pueden venir hasheadas por CSS Modules o ser cadenas largas de
 * utilidades Tailwind: nunca se usan como base de un selector.
 *
 * Se devuelve una lista ordenada por robustez; el primero es el preferido y el
 * resto queda guardado para que el runner futuro pueda hacer fallback.
 */

/** ids que un framework generó y que cambiarán en la siguiente ejecución. */
function looksAutoGenerated(id: string): boolean {
  return (
    /^:[a-z0-9]+:$/i.test(id) || // React useId: ":r1:", ":R2ab:"
    /^radix-/i.test(id) ||
    /^headlessui-/i.test(id) ||
    /^mui-\d/i.test(id) ||
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id) || // uuid
    /^[0-9]+$/.test(id) ||
    /^[a-f0-9]{16,}$/i.test(id) || // hash hexadecimal largo
    /^(react|ember|ng|svelte|vue)-[a-z0-9]{4,}$/i.test(id)
  )
}

function quote(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

/** Escape para usar un valor dentro de un selector de atributo CSS. */
function cssAttr(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

/** Escape del identificador de un `#id` en CSS (equivalente a CSS.escape). */
function cssIdent(value: string): string {
  return value.replace(/([^\w-])/g, '\\$1').replace(/^(\d)/, '\\3$1 ')
}

export function buildSelectorCandidates(signals: ElementSignals): SelectorCandidate[] {
  const candidates: SelectorCandidate[] = []
  const { matches } = signals

  // 1. data-testid: puesto ahí a propósito para pruebas; lo más estable que hay.
  if (signals.testId) {
    candidates.push({
      strategy: 'testid',
      value: `[data-testid="${cssAttr(signals.testId)}"]`,
      score: matches.testId === 1 ? 100 : 80
    })
  }

  // 2. id, solo si no parece autogenerado por el framework.
  if (signals.id && !looksAutoGenerated(signals.id)) {
    candidates.push({
      strategy: 'id',
      value: `#${cssIdent(signals.id)}`,
      score: matches.id === 1 ? 90 : 65
    })
  }

  // 3. rol ARIA + nombre accesible, en formato compatible con `page.getByRole`.
  if (signals.role && signals.accessibleName) {
    candidates.push({
      strategy: 'role',
      value: `role=${signals.role}[name="${quote(signals.accessibleName)}"]`,
      score: matches.roleName === 1 ? 85 : 55
    })
  }

  // 4. texto visible exacto, compatible con `page.getByText`.
  if (signals.text && signals.text.length <= 60) {
    candidates.push({
      strategy: 'text',
      value: `text="${quote(signals.text)}"`,
      score: matches.text === 1 ? 70 : 40
    })
  }

  // 5. último recurso: CSS estructural corto, ya filtrado de clases inestables.
  if (signals.cssPath) {
    candidates.push({
      strategy: 'css',
      value: signals.cssPath,
      score: matches.cssPath === 1 ? 45 : 20
    })
  }

  // Si nada de lo anterior aplicó, al menos se registra el tag con sus atributos
  // semánticos para que el paso no quede sin selector.
  if (candidates.length === 0) {
    const attrs: string[] = []
    if (signals.name) attrs.push(`[name="${cssAttr(signals.name)}"]`)
    if (signals.placeholder) attrs.push(`[placeholder="${cssAttr(signals.placeholder)}"]`)
    if (signals.type) attrs.push(`[type="${cssAttr(signals.type)}"]`)
    candidates.push({
      strategy: 'css',
      value: `${signals.tag}${attrs.join('')}`,
      score: attrs.length ? 30 : 10
    })
  }

  return candidates.sort((a, b) => b.score - a.score)
}
